{
  "exp_name": "mobilenet_v2_exp1",
  "batch_size": 256,
  "lr": 0.01,
  "lr_drop_step": 24,
  "epochs": 60,
  "init_epoch": 0,
  "num_workers": 20,
  "train_dir": '/media/datasets/imagenet_2012/images/train/',
  "val_dir": '/media/datasets/imagenet_2012/images/val/',
  "model":{"type": "resnet18",
           "pretrained_model": null}
}